import { Camera, CheckCircle2, ScanLine, TriangleAlert } from 'lucide-react'
import Link from 'next/link'
import { PageHead } from '../../../components/page-head'
import { loadVisionOperationsData } from '../../../lib/remaining-domain-data'
import { formatEnum, formatRelativeTime } from '../../../lib/work-items'
import { OpsPhoneRestriction } from '../../../components/ops-phone-restriction'
import { OpsPermissionRestriction } from '../../../components/ops-permission-restriction'
import { isRestrictedOpsPhoneRequest } from '../../../lib/client-surface'
import { hasOpsAreaAccess } from '../../../lib/route-access'

export const dynamic = 'force-dynamic'

const visionViews = new Set(['scans', 'review', 'completed', 'failed'])

export default async function VisionPage({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  if (!(await hasOpsAreaAccess('vision'))) return <OpsPermissionRestriction area="Measurements & Vision" />
  if (await isRestrictedOpsPhoneRequest()) return <OpsPhoneRestriction area="Measurements & Vision" />
  const [data, query] = await Promise.all([loadVisionOperationsData(), searchParams])
  const selectedView = visionViews.has(String(query.view)) ? String(query.view) : null
  const review = data.scans.filter((scan) => scan.requiresReview || scan.status === 'TAILOR_REVIEW_REQUIRED').length
  const failed = data.sessions.filter((session) => session.eventType === 'FAILED').length
  const completed = data.sessions.filter((session) => session.eventType === 'COMPLETED').length
  const visibleScans = selectedView === 'review' ? data.scans.filter((scan) => scan.requiresReview || scan.status === 'TAILOR_REVIEW_REQUIRED') : data.scans
  const visibleSessions = selectedView === 'completed' ? data.sessions.filter((session) => session.eventType === 'COMPLETED') : selectedView === 'failed' ? data.sessions.filter((session) => session.eventType === 'FAILED') : data.sessions
  return <><PageHead eyebrow="Marketplace / Vision" title="Measurements & Vision" description="Capture health and review exceptions without placing body measurements or private snapshots in an operational list." meta={`Observed ${formatRelativeTime(data.observedAt)}`} />
    <section className="ops-summary-grid"><Link className="ops-summary-cell ops-summary-link" href="/ops/vision?view=scans#scan-ledger"><div className="ops-summary-label">Saved scans</div><div className="ops-summary-value">{data.scans.length}</div><div className="ops-summary-detail">Authoritative measurement records</div></Link><Link className="ops-summary-cell ops-summary-link" href="/ops/vision?view=review#scan-ledger"><div className="ops-summary-label">Tailor review</div><div className="ops-summary-value">{review}</div><div className="ops-summary-detail">Explicit review requirement</div></Link><Link className="ops-summary-cell ops-summary-link" href="/ops/vision?view=completed#session-ledger"><div className="ops-summary-label">Completed sessions</div><div className="ops-summary-value">{completed}</div><div className="ops-summary-detail">Capture telemetry only</div></Link><Link className="ops-summary-cell ops-summary-link" href="/ops/vision?view=failed#session-ledger"><div className="ops-summary-label">Failed sessions</div><div className="ops-summary-value">{failed}</div><div className="ops-summary-detail">Operational recovery signal</div></Link></section>
    <div className="ops-status-banner ops-banner-after-grid" data-tone="healthy"><ScanLine size={16} />Body values, source frames, and measurement snapshots are intentionally excluded from this route. Open a purpose-limited case only when support requires them.</div>
    {(selectedView == null || selectedView === 'scans' || selectedView === 'review') ? <section className="ops-section-block" id="scan-ledger"><div className="ops-section-head"><div><p className="ops-action-label">Recent capture</p><h2>{selectedView === 'review' ? 'Scans requiring review' : 'Scan outcomes'}</h2></div><div className="ops-section-actions">{selectedView ? <Link className="ops-button" href="/ops/vision#scan-ledger">Clear filter</Link> : null}<span className="ops-muted">No body data in list view</span></div></div>{visibleScans.length ? <div className="ops-domain-list">{visibleScans.map((scan) => <article className="ops-domain-row ops-domain-row-compact" key={scan.id}><span className="ops-provider-icon" data-tone={scan.status === 'TAILOR_REVIEWED' ? 'healthy' : scan.requiresReview ? 'warning' : 'neutral'}>{scan.status === 'TAILOR_REVIEWED' ? <CheckCircle2 size={16} /> : <Camera size={16} />}</span><div><strong>{formatEnum(scan.captureMethod)}</strong><small>{scan.version} · {formatRelativeTime(scan.createdAt)}</small></div><div><span className="ops-label">Outcome</span><strong>{formatEnum(scan.status)}</strong><small>{scan.confidence ? `${formatEnum(scan.confidence)} confidence` : 'Confidence not recorded'}</small></div><div><span className="ops-label">Review</span><strong>{scan.requiresReview ? 'Tailor review required' : 'No exception'}</strong><small>Scan {scan.id}</small></div></article>)}</div> : <div className="ops-empty"><ScanLine size={20} /><h2>No eligible Vision scan</h2><p>The selected source set is empty. No simulated scan has been added.</p></div>}</section> : null}
    {(selectedView == null || selectedView === 'completed' || selectedView === 'failed') ? <section className="ops-section-block" id="session-ledger"><div className="ops-section-head"><div><p className="ops-action-label">Privacy-safe telemetry</p><h2>{selectedView ? `${formatEnum(selectedView)} capture sessions` : 'Capture session outcomes'}</h2></div><div className="ops-section-actions">{selectedView ? <Link className="ops-button" href="/ops/vision#session-ledger">Clear filter</Link> : null}<span className="ops-muted">No frames or body values</span></div></div>{visibleSessions.length ? <div className="ops-domain-list">{visibleSessions.map((session) => <article className="ops-domain-row ops-domain-row-compact" key={session.id}><span className="ops-provider-icon" data-tone={session.eventType === 'FAILED' ? 'critical' : session.eventType === 'COMPLETED' ? 'healthy' : 'neutral'}>{session.eventType === 'FAILED' ? <TriangleAlert size={16} /> : <Camera size={16} />}</span><div><strong>{formatEnum(session.eventType)}</strong><small>{formatEnum(session.mode)} · {formatRelativeTime(session.createdAt)}</small></div><div><span className="ops-label">Capture</span><strong>{session.captureCount} run{session.captureCount === 1 ? '' : 's'}</strong><small>{session.frameCount} privacy-safe frame count</small></div><div><span className="ops-label">Version</span><strong>{session.version}</strong><small>Session {session.sessionId}</small></div></article>)}</div> : <div className="ops-empty"><ScanLine size={20} /><h2>No eligible capture session</h2><p>The selected telemetry outcome has no source record in the bounded window.</p></div>}</section> : null}
    {failed > 0 ? <div className="ops-status-banner" data-tone="warning"><TriangleAlert size={16} />{failed} recent session failure{failed === 1 ? '' : 's'} should be correlated with device and release telemetry before contacting a customer.</div> : null}
  </>
}
