import { PackageCheck, Route, TriangleAlert } from 'lucide-react'
import Link from 'next/link'
import { OpsPhoneRestriction } from '../../../components/ops-phone-restriction'
import { OpsPermissionRestriction } from '../../../components/ops-permission-restriction'
import { PageHead } from '../../../components/page-head'
import { isRestrictedOpsPhoneRequest } from '../../../lib/client-surface'
import { loadDeliveryOperationsData } from '../../../lib/remaining-domain-data'
import { hasOpsAreaAccess } from '../../../lib/route-access'
import { formatEnum, formatRelativeTime } from '../../../lib/work-items'

export const dynamic = 'force-dynamic'

function money(amount: number, currency: string) { try { return new Intl.NumberFormat('en', { style: 'currency', currency }).format(amount / 100) } catch { return `${currency} ${(amount / 100).toFixed(2)}` } }

const deliveryViews = new Set(['active', 'in-transit', 'shortfall', 'exceptions'])
const transitStates = new Set(['BOOKED', 'CARRIER_ACCEPTED', 'COLLECTED', 'AT_HUB', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'RETURNING'])

export default async function DeliveryPage({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  if (!(await hasOpsAreaAccess('delivery'))) return <OpsPermissionRestriction area="Delivery & Supply" />
  if (await isRestrictedOpsPhoneRequest()) return <OpsPhoneRestriction area="Delivery & Supply" />
  const [data, query] = await Promise.all([loadDeliveryOperationsData(), searchParams])
  const selectedView = deliveryViews.has(String(query.view)) ? String(query.view) : null
  const active = data.runs.filter((run) => !['DELIVERED', 'PICKED_UP', 'CANCELLED', 'RECONCILED'].includes(run.status))
  const exceptions = data.runs.filter((run) => run.status === 'EXCEPTION' || run.fundingStatus === 'EXCEPTION' || run.refundStatus === 'FAILED')
  const shortfall = data.runs.filter((run) => run.fundingStatus === 'SHORTFALL_DUE')
  const inTransit = data.parcels.filter((parcel) => transitStates.has(parcel.status))
  const runs = selectedView === 'active' ? active : selectedView === 'shortfall' ? shortfall : selectedView === 'exceptions' ? exceptions : data.runs
  return <><PageHead eyebrow="Marketplace / Delivery" title="Delivery & supply" description="Fulfilment funding, custody, parcel movement, method changes, refunds, and exception recovery in one linked lane." meta={`Observed ${formatRelativeTime(data.observedAt)}`} />
    <section className="ops-summary-grid"><Link className="ops-summary-cell ops-summary-link" href="/ops/delivery?view=active#fulfilment-ledger"><div className="ops-summary-label">Active runs</div><div className="ops-summary-value">{active.length}</div><div className="ops-summary-detail">Not terminal or reconciled</div></Link><Link className="ops-summary-cell ops-summary-link" href="/ops/delivery?view=in-transit#parcel-ledger"><div className="ops-summary-label">In transit</div><div className="ops-summary-value">{inTransit.length}</div><div className="ops-summary-detail">Parcels with live custody</div></Link><Link className="ops-summary-cell ops-summary-link" href="/ops/delivery?view=shortfall#fulfilment-ledger"><div className="ops-summary-label">Shortfall due</div><div className="ops-summary-value">{shortfall.length}</div><div className="ops-summary-detail">Customer action before booking</div></Link><Link className="ops-summary-cell ops-summary-link" href="/ops/delivery?view=exceptions#fulfilment-ledger"><div className="ops-summary-label">Exceptions</div><div className="ops-summary-value">{exceptions.length}</div><div className="ops-summary-detail">Funding, provider, or refund recovery</div></Link></section>
    {selectedView !== 'in-transit' ? <section className="ops-section-block" id="fulfilment-ledger"><div className="ops-section-head"><div><p className="ops-action-label">Custody command</p><h2>{selectedView ? `${formatEnum(selectedView)} fulfilment runs` : 'Fulfilment runs'}</h2></div><div className="ops-section-actions">{selectedView ? <Link className="ops-button" href="/ops/delivery#fulfilment-ledger">Clear filter</Link> : null}<Link className="ops-button" href="/ops/queues/delivery">Open delivery cases</Link></div></div>{runs.length ? <div className="ops-domain-list">{runs.map((run) => <Link aria-label={`Open order ${run.orderId}`} className="ops-domain-row ops-domain-row-link" href={`/ops/orders/${run.orderId}`} key={run.id}><span className="ops-provider-icon" data-tone={run.status === 'EXCEPTION' ? 'critical' : ['DELIVERED', 'PICKED_UP', 'RECONCILED'].includes(run.status) ? 'healthy' : 'warning'}>{run.status === 'EXCEPTION' ? <TriangleAlert size={16} /> : <Route size={16} />}</span><div><strong>Order {run.orderId}</strong><small>{run.provider ?? 'Provider not booked'} · updated {formatRelativeTime(run.updatedAt)}</small></div><div><span className="ops-label">Run</span><strong>{formatEnum(run.status)}</strong><small>{formatEnum(run.method)} · {run.parcelCount} parcel{run.parcelCount === 1 ? '' : 's'}</small></div><div><span className="ops-label">Funding</span><strong>{formatEnum(run.fundingStatus)}</strong><small>{run.shortfallAmount > 0 ? `${money(run.shortfallAmount, run.currency)} due` : `${money(run.capturedAllowanceAmount, run.currency)} allowance`}</small></div><div><span className="ops-label">Last custody event</span><strong>{run.lastEvent ? formatEnum(run.lastEvent) : 'No event yet'}</strong><small>{run.correlationId}</small></div></Link>)}</div> : <div className="ops-empty"><PackageCheck size={20} /><h2>No eligible fulfilment run</h2><p>The selected authoritative source set is empty.</p></div>}</section> : null}
    {(selectedView == null || selectedView === 'in-transit') ? <section className="ops-section-block" id="parcel-ledger"><div className="ops-section-head"><div><p className="ops-action-label">Custody source set</p><h2>{selectedView === 'in-transit' ? 'Parcels in transit' : 'Recent parcels'}</h2></div><div className="ops-section-actions">{selectedView ? <Link className="ops-button" href="/ops/delivery#parcel-ledger">Clear filter</Link> : null}<span className="ops-muted">Tracking values are operationally restricted</span></div></div>{(selectedView === 'in-transit' ? inTransit : data.parcels).length ? <div className="ops-domain-list">{(selectedView === 'in-transit' ? inTransit : data.parcels).map((parcel) => <Link aria-label={`Open order ${parcel.orderId}`} className="ops-domain-row ops-domain-row-compact ops-domain-row-link" href={`/ops/orders/${parcel.orderId}`} key={parcel.id}><span className="ops-provider-icon" data-tone={transitStates.has(parcel.status) ? 'warning' : 'healthy'}><PackageCheck size={16} /></span><div><strong>Order {parcel.orderId}</strong><small>Run {parcel.runId} · updated {formatRelativeTime(parcel.updatedAt)}</small></div><div><span className="ops-label">Custody</span><strong>{formatEnum(parcel.status)}</strong><small>{parcel.provider ? formatEnum(parcel.provider) : 'Provider not recorded'}</small></div><div><span className="ops-label">Service</span><strong>{parcel.serviceLevel ? formatEnum(parcel.serviceLevel) : 'Not recorded'}</strong><small>{parcel.lastStatusAt ? `Observed ${formatRelativeTime(parcel.lastStatusAt)}` : 'No status timestamp'}</small></div></Link>)}</div> : <div className="ops-empty"><PackageCheck size={20} /><h2>No eligible parcel</h2><p>The selected custody source set is empty.</p></div>}</section> : null}
  </>
}
