export type OpsServiceQueue =
  | 'support'
  | 'privacy'
  | 'trust'
  | 'money'
  | 'delivery'
  | 'reliability'
  | 'operations'

export type OpsServiceDefinition = {
  key: string
  label: string
  queues: readonly OpsServiceQueue[]
  owners: readonly string[]
  caseTypes: readonly string[]
  authority: string
  runbooks: readonly OpsServiceQueue[]
  records: string
  terminalProof: string
  href: string
}

export type OpsQueueDefinition = {
  key: OpsServiceQueue
  label: string
  policy: string
  primary: string
  backup: string
  runbook: string
  firstResponse: string
  activeResolution: string
  firstAction: string
  escalateWhen: string
}

export const OPS_QUEUE_CATALOGUE: readonly OpsQueueDefinition[] = Object.freeze([
  { key: 'support', label: 'Support', policy: 'support-v1', primary: 'Customer Success', backup: 'Operations', runbook: 'docs/v1-decisions-support-sla-and-ops-priority-matrix.md', firstResponse: 'P0 4h · P1 24h · P2 48h · P3 72h · P4 7d', activeResolution: 'P0 24h · P1/P2 72h · P3 7d · P4 14d', firstAction: 'Confirm the named customer, exact workflow context, current authoritative state, and promised next update.', escalateWhen: 'Security, trust, money, or platform authority is required; the customer impact exceeds the queue; or the next safe action is undefined.' },
  { key: 'privacy', label: 'Privacy & deletion', policy: 'privacy-deletion-v1', primary: 'Customer Success', backup: 'Admin', runbook: 'docs/internal-control-plane-security-observability.md', firstResponse: 'P0 4h · P1 24h · P2 48h · P3 72h · P4 7d', activeResolution: '30d for every priority', firstAction: 'Verify the durable request, current blockers, eligible data copies, and any narrowly documented retention exception.', escalateWhen: 'The deadline is at risk, a legal-hold or finance exception is unclear, propagation fails, or irreversible execution needs fresh step-up.' },
  { key: 'trust', label: 'Trust & safety', policy: 'trust-safety-v1', primary: 'Trust', backup: 'Admin', runbook: 'docs/internal-control-plane-security-observability.md', firstResponse: 'P0 4h · P1 24h · P2 48h · P3 72h · P4 7d', activeResolution: 'P0 24h · P1 72h · P2 5d · P3 7d · P4 14d', firstAction: 'Review the purpose-limited randomized challenge video, profile, portfolio, and current visibility state; never request government ID.', escalateWhen: 'There is an appeal, safety report, evidence-access anomaly, high-risk restriction, or policy ambiguity.' },
  { key: 'money', label: 'Money Desk', policy: 'commercial-prelaunch-founder-v1', primary: 'Finance', backup: 'Admin', runbook: 'docs/ops-order-runbook.md', firstResponse: 'P0 4h · P1 24h · P2 48h · P3 72h · P4 7d', activeResolution: 'P0 24h · P1 72h · P2 5d · P3 7d · P4 14d', firstAction: 'Reconcile Drapeon ledger state with the provider reference before preparing, approving, or repeating any movement.', escalateWhen: 'Provider outcome is ambiguous, the ledger disagrees, founder authority is unavailable, or scoped elevation expires.' },
  { key: 'delivery', label: 'Delivery & supply', policy: 'delivery-supply-v1', primary: 'Operations', backup: 'Customer Success', runbook: 'docs/ops-order-runbook.md', firstResponse: 'P0 4h · P1 24h · P2 48h · P3 72h · P4 7d', activeResolution: 'P0 24h · P1 72h · P2 5d · P3 7d · P4 14d', firstAction: 'Identify the authoritative fulfilment run, custody state, active replacement request, and exact next carrier or counterpart action.', escalateWhen: 'Custody is unclear, a superseded path remains usable, provider state conflicts, or the customer promise is at risk.' },
  { key: 'reliability', label: 'Reliability', policy: 'reliability-v1', primary: 'Engineering', backup: 'Admin', runbook: 'docs/service-health-and-monitoring.md', firstResponse: 'P0 15m · P1 1h · P2 24h · P3 72h · P4 7d', activeResolution: 'P0 1h · P1 4h · P2 24h · P3 72h · P4 7d', firstAction: 'Validate the Drapeon-owned synthetic, durable observation, affected customer path, and last healthy transition before changing a provider.', escalateWhen: 'Monitor silence exceeds 12m, customer impact is critical, a queue is dead-lettering, or no bounded recovery owner exists.' },
  { key: 'operations', label: 'Marketplace operations', policy: 'operations-v1', primary: 'Operations', backup: 'Admin', runbook: 'docs/ops-order-runbook.md', firstResponse: 'P0 4h · P1 24h · P2 48h · P3 72h · P4 7d', activeResolution: 'P0 24h · P1 72h · P2 5d · P3 7d · P4 14d', firstAction: 'Confirm the authoritative order or marketplace stage, current owner, next valid action, and counterpart-visible state.', escalateWhen: 'No catalogue workflow applies, a cross-domain authority is needed, or an adjacent user surface contradicts the authoritative record.' },
])

export const OPS_SERVICE_CATALOGUE: readonly OpsServiceDefinition[] = Object.freeze([
  { key: 'account-access', label: 'Authentication, onboarding, role switch, and recovery', queues: ['support'], owners: ['Customer Success'], caseTypes: ['SYSTEM_ALERT', 'AFTERCARE_REQUEST'], authority: 'Support triage; Engineering owns security anomalies.', runbooks: ['support'], records: 'Auth identity, users, role profiles, and security events', terminalProof: 'Confirmed account state and terminal communication outcome; security anomalies escalate to Engineering.', href: '/ops/customers' },
  { key: 'privacy-deletion', label: 'Customer privacy, deletion, and data requests', queues: ['privacy'], owners: ['Customer Success'], caseTypes: ['ACCOUNT_DELETION_REQUEST', 'DATA_ACCESS_REQUEST'], authority: 'Customer Success reviews; Admin plus fresh step-up executes deletion.', runbooks: ['privacy'], records: 'Deletion request, case, event, and action-receipt ledgers', terminalProof: 'Completed propagation or a documented blocker or legal exception; execution requires fresh step-up.', href: '/ops/customers?view=deletion#customer-roster' },
  { key: 'tailor-acquisition', label: 'Tailor acquisition and studio setup', queues: ['trust', 'operations'], owners: ['Trust'], caseTypes: ['TAILOR_APPLICATION', 'TAILOR_VERIFICATION'], authority: 'Trust decides readiness; Operations resolves setup workflow gaps.', runbooks: ['trust', 'operations'], records: 'Tailor applications, profiles, portfolio proof, and readiness state', terminalProof: 'Application and profile outcome with the exact next requirement; no public listing before readiness.', href: '/ops/tailors?view=applications#application-roster' },
  { key: 'tailor-trust', label: 'Tailor challenge-video trust review', queues: ['trust'], owners: ['Trust'], caseTypes: ['TAILOR_VERIFICATION', 'CONTENT_FLAG', 'SELLER_ACCESS_REVIEW'], authority: 'Trust or Admin with fresh step-up may decide or restrict.', runbooks: ['trust'], records: 'Tailor trust state, private challenge reference, case, and receipt', terminalProof: 'Approve, reject, or restrict receipt plus the resulting public visibility; payout readiness stays independent.', href: '/ops/trust' },
  { key: 'catalogue-quality', label: 'Public catalogue and showcase quality', queues: ['operations'], owners: ['Operations'], caseTypes: ['CONTENT_FLAG', 'SELLER_ACCESS_REVIEW'], authority: 'Operations handles visibility and stock; Trust owns safety restrictions.', runbooks: ['operations', 'trust'], records: 'Tailor profiles, seller items, inventory state, and public tombstones', terminalProof: 'Visible, hidden, or stock outcome plus invalidation proof; a cache may never resurrect removed content.', href: '/ops/tailors' },
  { key: 'conversation-safety', label: 'Customer–tailor conversation and safety', queues: ['support', 'trust'], owners: ['Customer Success', 'Trust'], caseTypes: ['CONVERSATION_SAFETY', 'CONTACT_BYPASS', 'CONTENT_FLAG', 'AFTERCARE_REQUEST'], authority: 'Customer Success restores access; Trust decides moderation or restriction.', runbooks: ['support', 'trust'], records: 'Conversation access, safety reports, cases, and communication outcomes', terminalProof: 'Access, moderation, or remedy outcome without copying private messages into generic logs.', href: '/ops/communications' },
  { key: 'consultations', label: 'Consultations and live calls', queues: ['operations', 'support'], owners: ['Operations'], caseTypes: ['ORDER_REVIEW', 'AFTERCARE_REQUEST'], authority: 'Operations owns attendance and reschedule; Support owns customer recovery.', runbooks: ['operations', 'support'], records: 'Order consultation state, attendance, reschedule, and call-provider outcomes', terminalProof: 'Attendance or reschedule outcome, terminal notification, and an exact order deep link.', href: '/ops/orders' },
  { key: 'orders', label: 'Custom and ready-made orders', queues: ['operations'], owners: ['Operations'], caseTypes: ['ORDER_REVIEW', 'AFTERCARE_REQUEST', 'PRODUCTION_STALL', 'FABRIC_APPROVAL'], authority: 'Operations may advance only server-authorized order transitions.', runbooks: ['operations'], records: 'Orders, stages, events, payments, approvals, and fulfilment', terminalProof: 'Authoritative transition, durable receipt, counterpart refresh, and every queued side effect terminal.', href: '/ops/orders' },
  { key: 'vision', label: 'Measurements and Drapeon Vision', queues: ['operations', 'reliability'], owners: ['Operations', 'Engineering'], caseTypes: ['ORDER_REVIEW', 'SYSTEM_ALERT'], authority: 'Operations handles review outcomes; Engineering owns capture/runtime failure.', runbooks: ['operations', 'reliability'], records: 'Measurement profile, scan metadata, capture logs, and cases', terminalProof: 'Saved, review-required, or failed outcome; body values and source frames never enter list views.', href: '/ops/vision' },
  { key: 'fulfilment', label: 'Fulfilment switching, delivery, and supply', queues: ['delivery'], owners: ['Operations'], caseTypes: ['DELIVERY_REVIEW', 'FULFILLMENT_RECONCILIATION_FAILED', 'ORDER_REVIEW'], authority: 'Operations controls fulfilment transitions; money effects route to Finance.', runbooks: ['delivery'], records: 'Fulfilment runs, parcels, events, and change requests', terminalProof: 'Accepted, paid, rejected, cancelled, or recovered outcome with every superseded path removed.', href: '/ops/delivery' },
  { key: 'money', label: 'Payments, charges, tips, refunds, payouts, and settlement', queues: ['money'], owners: ['Finance'], caseTypes: ['PAYMENT_BLOCKED', 'PAYOUT_BLOCKED', 'PAYOUT_FAILED', 'REFUND_FAILED', 'ESCROW_STUCK', 'DOUBLE_CHARGE_RISK', 'FABRIC_APPROVAL'], authority: 'The configured founder account with fresh step-up during prelaunch.', runbooks: ['money'], records: 'Payments, Money Desk requests, decisions, grants, attempts, callbacks, and settlement', terminalProof: 'Provider-reconciled terminal outcome and receipt; ambiguous provider state is never blindly retried.', href: '/ops/money' },
  { key: 'communications', label: 'Push, email, SMS, and reviewed campaigns', queues: ['operations', 'reliability'], owners: ['Customer Success', 'Engineering'], caseTypes: ['SYSTEM_ALERT'], authority: 'Customer Success owns content; Engineering owns delivery infrastructure.', runbooks: ['operations', 'reliability'], records: 'Job queue, campaign recipients, and provider events', terminalProof: 'Delivered, failed, dead, or suppressed terminal result; queued never means delivered.', href: '/ops/communications' },
  { key: 'providers', label: 'Providers, callbacks, queues, schedulers, and synthetics', queues: ['reliability'], owners: ['Engineering'], caseTypes: ['SYSTEM_ALERT', 'WEBHOOK_ERROR', 'PAYOUT_FAILED', 'REFUND_FAILED', 'FULFILLMENT_RECONCILIATION_FAILED'], authority: 'Engineering or Admin operates recovery; provider truth must be reconciled.', runbooks: ['reliability'], records: 'Monitor ledger, provider circuits, jobs, and incidents', terminalProof: 'Drapeon-owned recovery observation and incident transition; vendor status alone is insufficient.', href: '/ops/providers' },
  { key: 'governance', label: 'Workforce access, offboarding, exports, and audit', queues: ['operations'], owners: ['Admin'], caseTypes: ['DATA_ACCESS_REQUEST', 'SYSTEM_ALERT'], authority: 'Admin only; fresh step-up and separation apply to sensitive actions.', runbooks: ['operations'], records: 'Workforce principals, session cutoffs, push subscriptions, receipts, events, and audits', terminalProof: 'Revocation or export completion reconciled across every target and retained as durable evidence.', href: '/ops/admin/access' },
])
