import { useCallback, useEffect, useMemo, useState } from 'react'
import { Alert, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import { Feather } from '@expo/vector-icons'
import {
  formatMoneyInputValue,
  normalizeAccountCurrency,
  parseMoneyInputToMinorUnits,
} from '@drape/shared'
import { Colors, FontSize, FontWeight, Radius, Spacing } from '@/constants/theme'
import { useOrderPaymentFlow } from '@/lib/payments'
import { supabase } from '@/lib/supabase'
import { MoneyInput } from './MoneyInput'

type Tip={id:string;amount:number;currency:string;status:string}
export function OrderTipCard({orderId,actorRole,currency,customerEmail,customerName,onChanged}:{orderId:string;actorRole:'CUSTOMER'|'TAILOR';currency:string|null;customerEmail?:string|null;customerName?:string|null;onChanged?:()=>void|Promise<void>}){
  const [tip,setTip]=useState<Tip|null>(null);const [amount,setAmount]=useState('');const [busy,setBusy]=useState(false);const {startOrderTip}=useOrderPaymentFlow()
  const currencyCode=normalizeAccountCurrency(currency)??'USD'
  const refresh=useCallback(async()=>{const {data}=await supabase.from('order_tips').select('id, amount, currency, status').eq('order_id',orderId).maybeSingle();setTip(data)},[orderId]);useEffect(()=>{void refresh()},[refresh])
  const suggestions=useMemo(()=>currencyCode==='NGN'?['1000','2500','5000']:['5','10','20'],[currencyCode])
  const send=async(overrideMinor?:number)=>{const parsed=overrideMinor??parseMoneyInputToMinorUnits(amount);if(!parsed)return Alert.alert('Enter a valid tip','Choose a suggestion or enter an amount.');setBusy(true);const result=await startOrderTip({orderId,amount:parsed,currency:currencyCode,customerEmail,customerName});setBusy(false);if(!result.ok)return Alert.alert(result.reason==='cancelled'?'Tip not completed':'Tip unavailable',result.message);await refresh();await onChanged?.();Alert.alert('Tip confirmed','The full displayed amount is owed to the tailor and is queued separately for payout.')}
  if(tip)return <View style={styles.card}><View style={styles.header}><View style={styles.icon}><Feather name="heart" size={17} color={Colors.needleGreen}/></View><View style={styles.flex}><Text style={styles.eyebrow}>{actorRole==='CUSTOMER'?'Your tip':'Customer tip'}</Text><Text style={styles.title}>{tip.currency} {(tip.amount/100).toLocaleString(undefined,{minimumFractionDigits:2})}</Text></View><View style={styles.status}><Text style={styles.statusText}>{tip.status.replaceAll('_',' ').toLowerCase()}</Text></View></View><Text style={styles.muted}>{actorRole==='TAILOR'?'The full displayed tip is yours. It stays separate from order earnings and is released through controlled payout.':'This stays separate from the order total, review, discounts, and tailor ranking.'}</Text>{actorRole==='CUSTOMER'&&tip.status==='FAILED'?<TouchableOpacity accessibilityRole="button" style={styles.primary} disabled={busy} onPress={()=>{void send(tip.amount)}}><Text style={styles.primaryText}>{busy?'Opening secure payment…':'Retry this tip'}</Text></TouchableOpacity>:null}</View>
  if(actorRole==='TAILOR')return null
  return <View style={styles.card}><View style={styles.header}><View style={styles.icon}><Feather name="heart" size={17} color={Colors.needleGreen}/></View><View style={styles.flex}><Text style={styles.eyebrow}>Optional thank-you</Text><Text style={styles.title}>Tip your tailor</Text></View></View><Text style={styles.muted}>Available after handoff. Drapeon takes no commission from the displayed tip.</Text><View style={styles.choices}>{suggestions.map(value=>{const formatted=formatMoneyInputValue(value);return <TouchableOpacity accessibilityRole="button" accessibilityState={{selected:amount===formatted}} key={value} style={[styles.choice,amount===formatted&&styles.active]} onPress={()=>setAmount(formatted)}><Text style={styles.choiceText}>{currencyCode} {formatted}</Text></TouchableOpacity>})}</View><MoneyInput label="Custom tip" accessibilityLabel="Custom tip amount" value={amount} onChangeText={setAmount} currency={currencyCode}/><TouchableOpacity accessibilityRole="button" style={styles.primary} disabled={busy} onPress={()=>{void send()}}><Text style={styles.primaryText}>{busy?'Opening secure payment…':'Send tip'}</Text></TouchableOpacity></View>
}
const styles=StyleSheet.create({card:{backgroundColor:Colors.white,borderWidth:1,borderColor:Colors.lightGrey,borderRadius:Radius.lg,padding:Spacing.lg,gap:Spacing.sm},header:{flexDirection:'row',alignItems:'center',gap:Spacing.sm},icon:{width:38,height:38,borderRadius:Radius.full,backgroundColor:Colors.needleGreenLight,alignItems:'center',justifyContent:'center'},flex:{flex:1},eyebrow:{fontSize:FontSize.xs,fontWeight:FontWeight.semibold,color:Colors.needleGreen,textTransform:'uppercase',letterSpacing:.4},title:{fontSize:FontSize.md,fontWeight:FontWeight.bold,color:Colors.ink},muted:{fontSize:FontSize.xs,lineHeight:18,color:Colors.inkLight},status:{backgroundColor:Colors.boneDeep,borderRadius:Radius.full,paddingHorizontal:Spacing.sm,paddingVertical:6},statusText:{fontSize:FontSize.xs,fontWeight:FontWeight.semibold,color:Colors.ink,textTransform:'capitalize'},choices:{flexDirection:'row',flexWrap:'wrap',gap:7},choice:{borderRadius:Radius.full,borderWidth:1,borderColor:Colors.lightGrey,backgroundColor:Colors.bone,paddingHorizontal:12,paddingVertical:8},active:{borderColor:Colors.needleGreen,backgroundColor:Colors.needleGreenLight},choiceText:{fontSize:FontSize.xs,fontWeight:FontWeight.semibold,color:Colors.ink},primary:{minHeight:48,borderRadius:Radius.full,backgroundColor:Colors.needleGreen,alignItems:'center',justifyContent:'center'},primaryText:{color:Colors.white,fontWeight:FontWeight.bold}})
